### ISSUE TITLE
Easyrtc clients in a call get dissconnected when the server is rebooted

### ISSUE THREAD

**Issue by krneticz** [open-easyrtc/open-easyrtc#101]
When you have two peers in a call and you reboot the server call gets disconnected, and it should not since it's P2P.

**Comment by krneticz** [comment]
@hthetiot can you please share the monkey patch that you have mentioned to prevent this behaviour? Thanks!

**Comment by hthetiot** [comment]
This use to do the trick, le me know.
```js
var hangup = easyrtc.hangup;

easyrtc.hangup = function (socketId, force) {
    if (force || easyrtc.getConnectStatus(socketId) === easyrtc.NOT_CONNECTED) {
        hangup(socketId);
    }
};
```

P.S Regarding redis, I have big PR comming with refactor of server for that.

**Comment by krneticz** [comment]
Thanks, man! I will try and let you know. Great to hear about the incoming PR!

**Comment by hthetiot** [comment]
I will check again, can you add breakpoint to see if the method is called when the server disconnect.

**Comment by krneticz** [comment]
I checked, and it's not being triggered.

**Comment by hthetiot** [comment]
Ok will will look at it later today.

**Comment by hthetiot** [comment]
@krneticz sorry for late reply.

You need this change on top of https://github.com/open-easyrtc/open-easyrtc/issues/101#issuecomment-1375726280 monkey patch. wil try making PR when i have a moment. Cause disconnect call HanupAll.

```diff
@@ -4681,7 +4668,6 @@ var Easyrtc = function() {
      */
     this.hangup = function(otherUser) {
         hangupBody(otherUser);
-        updateConfigurationInfo();
     };

     /**
@@ -4690,18 +4676,10 @@ var Easyrtc = function() {
      *    easyrtc.hangupAll();
      */
     this.hangupAll = function() {
-
-        var sawAConnection = false;
         for (var otherUser in peerConns) {
-            if (!peerConns.hasOwnProperty(otherUser)) {
-                continue;
+            if (peerConns.hasOwnProperty(otherUser)) {
+                this.hangup(otherUser);
             }
-            sawAConnection = true;
-            hangupBody(otherUser);
-        }
-
-        if (sawAConnection) {
-            updateConfigurationInfo();
         }
     };

```

**Comment by hthetiot** [comment]
No need to patch api/easyrtc.js i pushed fixes on master.
- https://github.com/open-easyrtc/open-easyrtc/commit/6c704d6df0064b93e9e746c8b006d9ae0ea26177

Can you try master and apply https://github.com/open-easyrtc/open-easyrtc/issues/101#issuecomment-1375726280 monkey patch and let me know if that works for you.

**Comment by krneticz** [comment]
@hthetiot thanks mate! Yes, it does the job! Just to make sure, rel 2.0.18 contains this fix?

**Comment by hthetiot** [comment]
@krneticz yes I did release yesterday for you.
It also includes a fix that caused hangup then call to hangup after few second due a bug on an empty array reduce. Notice that on disconnect you will receive room update with empty users.

**Comment by krneticz** [comment]
@hthetiot Unfortunately, after careful testing, we still have an issue here. Here is what happens: 
I check out code from the master branch, install libs, build easyrtc.js and then run demo http://localhost:8080/demos/demo_audio_video_simple.html in two tabs.

If I run it as is, as expected, after I  connect two instances in a video call and kill the server, they disconnect.
AfterI applying the given monkey patch in both tabs:
var hangup = easyrtc.hangup;
  easyrtc.hangup = function (socketId, force) {
      if (force || easyrtc.getConnectStatus(socketId) === easyrtc.NOT_CONNECTED) {
          hangup(socketId);
      }
  };

I connect parties again and kill the server- they stay connected to each other. BUT, when I rerun the server, they lose the connection! I tried multiple times and always had the same behaviour.

Please advise!

**Comment by hthetiot** [comment]
> I connect parties again and kill the server- they stay connected to each other. BUT, when I rerun the server, they lose the connection! I tried multiple times and always had the same behaviour.

Yeah they change easyrtcid so they hangup i think. Will se session might not bee needed, if needed with fix.
